services:
  torre-talent-explorer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: torre-talent-explorer-app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secrets
      - PORT=80
    depends_on:
      - db
    networks:
      - network

  db:
    image: mariadb
    container_name: torre-talent-explorer-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secrets
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - network

networks:
  network:
    driver: bridge